components:
  schemas:
    BlogPosting:
      description: "https://www.schema.org/BlogPosting"
      properties:
        alternativeHeadline:
          type: string
        articleBody:
          type: string
        caption:
          type: string
        contentSpace:
          $ref: ../../headless-person/headless-person-impl/openapi.yaml/components/schemas/ContentSpace
        dateCreated:
          format: date
          type: string
        dateModified:
          format: date
          type: string
        datePublished:
          format: date
          type: string
        description:
          type: string
        encodingFormat:
          type: string
        friendlyUrlPath:
          type: string
        headline:
          type: string
        keywords:
          items:
            type: string
          type: array
      type: object
info:
  description: ""
  title: ""
  version: 1.0.0
openapi: 3.0.1
paths:
  "/blog-posting/{id}":
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            "*/*": {}
          description: ""
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/BlogPosting"
      responses:
        200:
          content:
            "*/*":
              schema:
                items:
                  $ref: "#/components/schemas/BlogPosting"
                type: array
          description: ""
  "/content-space/{parent-id}/blog-posting":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: parent-id
          required: true
          schema:
            $ref: ../../headless-person/headless-person-impl/openapi.yaml/components/schemas/ContentSpace
      responses:
        200:
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""
    post:
      parameters:
        - in: path
          name: parent-id
          required: true
          schema:
            $ref: ../../headless-person/headless-person-impl/openapi.yaml/components/schemas/ContentSpace
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/BlogPosting"
      responses:
        200:
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/BlogPosting"
          description: ""