components:
  schemas:
    ContentSpace:
      properties:
        availableLanguages:
          items:
            type: string
          type: array
        author:
          $ref: "../../headless-person/headless-person-impl/openapi.yaml/components/schemas/Person"
        description:
          type: string
        id:
          type: integer
        name:
          type: string
        self:
          type: string
      type: object
info:
  description: ""
  title: ""
  version: 1.0.0
openapi: 3.0.1
paths:
  "/content-space":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
      responses:
        200:
          content:
            "*/*":
              schema:
                items:
                  $ref: "#/components/schemas/ContentSpace"
                type: array
          description: ""
  "/content-space/{id}":
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ContentSpace"
          description: ""