components:
  schemas:
    Person:
      properties:
        familyName:
          type: string
        id:
          type: integer
        self:
          type: string
      type: object
info:
  description: ""
  title: ""
  version: "1.0.0"
openapi: "3.0.1"
paths:
  "/person":
    get:
      responses:
        200:
          content:
            "*/*": {}
          description: ""
    post:
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        200:
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Person"
          description: description
  "/person/{id}":
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          content:
            "*/*": {}
          description: description
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            "*/*": {}
          description: ""
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        200:
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Person"
          description: description